# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "12:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "dependabot"
    commit-message:
      prefix: "deps"
    # Allow normal stable semver updates (major/minor/patch).
    # No ignore rules here, so stable updates are created.
