# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will test connection to the VPS, checking out
# the code, setting up Java, builds the code, and deploys
# the JAR to the temporary directory.
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Deploy Pokédex Reactor

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v5.7.0
        with:
          distribution: temurin
          java-version: '25'

      - name: Build Reactor JAR
        run: ./mvnw clean package
